reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
osx_image: xcode7

install:
  - bundle install
  - pod install --project-directory=Lock

script:
  - set -o pipefail && xcodebuild -workspace Lock/Lock.xcworkspace -scheme Lock -destination "platform=iOS Simulator,OS=latest,name=iPhone 6" clean build test | xcpretty -c

notifications:
  slack:
    secure: ZGaLexVgDGkvXMwhc8IklZJHZvI7N+SN+y1YD7WBH+yCw4cc+2CtNzHzNz7TuvRQjIXVbmgcBtKUGer9kcKTfnOrzHrW6K/XdkPNB9kGRUiQf/MnpyijbWpMyf7FZZnrzrwn1mADTG8tkYjV+N5fCYePvyyD/ancurSnC2T/H8E=

branches:
  only:
    - master