reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c

podfile: Examples/cocoapods-example/Podfile

before_install:
	- brew update
	- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
	- gem install cocoapods --no-ri --no-rdoc

script:
	- xctool -workspace Examples/cocoapods-example/Auth0Client.xcworkspace -scheme Auth0Client -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO clean test

notifications:
  slack:
    secure: ZGaLexVgDGkvXMwhc8IklZJHZvI7N+SN+y1YD7WBH+yCw4cc+2CtNzHzNz7TuvRQjIXVbmgcBtKUGer9kcKTfnOrzHrW6K/XdkPNB9kGRUiQf/MnpyijbWpMyf7FZZnrzrwn1mADTG8tkYjV+N5fCYePvyyD/ancurSnC2T/H8E=
