reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c

podfile: Lock/Podfile

before_install:
  - brew update
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
  - gem install cocoapods --no-ri --no-rdoc

script:
  - xctool -workspace Lock/Lock.xcworkspace -scheme Lock -sdk iphonesimulator -destination "platform=iOS Simulator,OS=latest,name=iPhone 6" ONLY_ACTIVE_ARCH=NO clean test

notifications:
  slack:
    secure: ZGaLexVgDGkvXMwhc8IklZJHZvI7N+SN+y1YD7WBH+yCw4cc+2CtNzHzNz7TuvRQjIXVbmgcBtKUGer9kcKTfnOrzHrW6K/XdkPNB9kGRUiQf/MnpyijbWpMyf7FZZnrzrwn1mADTG8tkYjV+N5fCYePvyyD/ancurSnC2T/H8E=

branches:
  only:
    - master