reference: http://www.objc.io/issue-6/travis-ci.html
language: objective-c
cache:
  - bundler
  - cocoapods
podfile: Example/Podfile
before_install:
  - gem install cocoapods --no-ri --no-rdoc
script:
  - xctool test -workspace Example/Auth0Client.xcworkspace -scheme Auth0Client -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

branches:
  - master
